eureka:
  client:
    service-url:
        defaultZone: http://www.ckh.com:7001/eureka/

  instance:
    instance-id: bro-cloud-provider-8080
    prefer-ip-address: true

info:
  app.name: bro-cloud-provider-8080

