server:
  port: 7001

eureka:
  instance:
    hostname: www.ckh.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/